<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>poppler-net</AssemblyName>
    <RootNamespace>Poppler.Cli</RootNamespace>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>poppler-net</ToolCommandName>
    <Version>0.9.0-rc.1</Version>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Poppler.Net\Poppler.Net.csproj" />
  </ItemGroup>
</Project>
