<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseAppHost>false</UseAppHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Poppler.Net\Poppler.Net.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NUnit" PrivateAssets="all" />
    <PackageReference Include="NUnitLite" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\fixtures\*.pdf"
          Link="Fixtures\%(Filename)%(Extension)"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\fixtures\encrypted-fixtures.json"
          Link="Fixtures\encrypted-fixtures.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\fixtures\font-fixtures.json"
          Link="Fixtures\font-fixtures.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\fixtures\graphics-fixture.json"
          Link="Fixtures\graphics-fixture.json"
          CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\fixtures\images-color-fixture.json"
          Link="Fixtures\images-color-fixture.json"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
